// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: wifinder_lvgl

#include "ui.h"

extern void toggleWifiScan();
extern void toggleSelectWifi();

void toggleScanWifiAction(lv_event_t *e)
{
  toggleWifiScan();
}

void toggleSelectWifiAction(lv_event_t *e)
{
  toggleSelectWifi();
}
