// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: wifinder_lvgl

#include "../ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0x1B1F31), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WifiSSIDListRoller = lv_roller_create(ui_Screen1);
    lv_roller_set_options(ui_WifiSSIDListRoller, "Wifi Item\nItem2", LV_ROLLER_MODE_NORMAL);
    lv_obj_set_width(ui_WifiSSIDListRoller, 180);
    lv_obj_set_height(ui_WifiSSIDListRoller, 200);
    lv_obj_set_x(ui_WifiSSIDListRoller, -100);
    lv_obj_set_y(ui_WifiSSIDListRoller, -5);
    lv_obj_set_align(ui_WifiSSIDListRoller, LV_ALIGN_CENTER);
    lv_obj_set_style_text_color(ui_WifiSSIDListRoller, lv_color_hex(0xC1C1C1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_WifiSSIDListRoller, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_WifiSSIDListRoller, lv_color_hex(0x20293A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_WifiSSIDListRoller, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_WifiSSIDListRoller, lv_color_hex(0x31415E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_WifiSSIDListRoller, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WifinderTitle = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_WifinderTitle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WifinderTitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WifinderTitle, 0);
    lv_obj_set_y(ui_WifinderTitle, 15);
    lv_obj_set_align(ui_WifinderTitle, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_WifinderTitle, "Scan WiFi");
    lv_obj_set_style_text_color(ui_WifinderTitle, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_WifinderTitle, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_WifinderTitle, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ToggleScanButton = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_ToggleScanButton, 120);
    lv_obj_set_height(ui_ToggleScanButton, 40);
    lv_obj_set_x(ui_ToggleScanButton, 10);
    lv_obj_set_y(ui_ToggleScanButton, -10);
    lv_obj_set_align(ui_ToggleScanButton, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_add_flag(ui_ToggleScanButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ToggleScanButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ToggleScanLabel = lv_label_create(ui_ToggleScanButton);
    lv_obj_set_width(ui_ToggleScanLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ToggleScanLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ToggleScanLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ToggleScanLabel, "Stop Scan");

    ui_RSSIArc = lv_arc_create(ui_Screen1);
    lv_obj_set_width(ui_RSSIArc, 150);
    lv_obj_set_height(ui_RSSIArc, 150);
    lv_obj_set_x(ui_RSSIArc, 100);
    lv_obj_set_y(ui_RSSIArc, -5);
    lv_obj_set_align(ui_RSSIArc, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_RSSIArc, LV_STATE_USER_3);       /// States
    lv_obj_clear_flag(ui_RSSIArc, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_arc_set_range(ui_RSSIArc, -120, 0);
    lv_arc_set_value(ui_RSSIArc, -60);

    lv_obj_set_style_arc_color(ui_RSSIArc, lv_color_hex(0xE7B416), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_RSSIArc, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_RSSIArc, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RSSIArc, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_RSSIArc, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_RSSIArc, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_RSSIArc, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_RSSIArc, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_RSSILabel = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_RSSILabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RSSILabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_RSSILabel, 100);
    lv_obj_set_y(ui_RSSILabel, -5);
    lv_obj_set_align(ui_RSSILabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_RSSILabel, "-");
    lv_obj_set_style_text_color(ui_RSSILabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_RSSILabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_RSSILabel, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ToggleSelectWifiButton = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_ToggleSelectWifiButton, 120);
    lv_obj_set_height(ui_ToggleSelectWifiButton, 40);
    lv_obj_set_x(ui_ToggleSelectWifiButton, -10);
    lv_obj_set_y(ui_ToggleSelectWifiButton, -10);
    lv_obj_set_align(ui_ToggleSelectWifiButton, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_add_flag(ui_ToggleSelectWifiButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ToggleSelectWifiButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ToggleSelectWifiLabel = lv_label_create(ui_ToggleSelectWifiButton);
    lv_obj_set_width(ui_ToggleSelectWifiLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ToggleSelectWifiLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ToggleSelectWifiLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ToggleSelectWifiLabel, "Select WiFi");

    lv_obj_add_event_cb(ui_ToggleScanButton, ui_event_ToggleScanButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ToggleSelectWifiButton, ui_event_ToggleSelectWifiButton, LV_EVENT_ALL, NULL);

}
